name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-github-runtime@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: v0.5.1
          driver-opts: image=tonistiigi/buildkit:github-actions-cache
      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker-meta
        with:
          images: gcr.io/hu-tao-supremacy-305006/personalization-core
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: hu-tao-supremacy-305006
          service_account_key: ${{ secrets.CLOUD_FUNCTIONS_CREDENTIALS }}
          export_default_credentials: true
      - run: gcloud auth configure-docker
      - uses: docker/build-push-action@v2
        id: docker-build
        with:
          cache-from: type=gha
          cache-to: type=gha
          context: .
          file: ./Dockerfile
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          push: true
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --image gcr.io/hu-tao-supremacy-305006/personalization-core \
            --platform managed \
            --add-cloudsql-instances ${{ secrets.CLOUD_SQL_INSTANCE }} \
            --update-env-vars INSTANCE_CONNECTION_NAME="${{ secrets.CLOUD_SQL_INSTANCE }}"
        env:
          SERVICE: personalization-core
          REGION: asia-southeast1
